version: '3'

services:
  mysql:
    image: mysql:8.0  # Specify MySQL version
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Named volume
    restart: always
    # Remove the command line if using MySQL 5.7
    # command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
